### PR TITLE
Make DialogOverlay extending native HTMLDialogElement.

### LINKED ISSUE #542: [dialog-overlay] Rework to use <dialog>
This should improve the user experience with dialogs, and will indirectly fix #448.

### PR DESCRIPTION
**Pull request by fabiocaccamo**
Fixes #448 
Fixes #542 

This PR makes the dialog by extending the native `<dialog>` element and brings the following improvements:
- Tabbing is natively trapped inside the dialog when it's open
- Escape for closing the dialog is natively supported
- The dialog theme is sync to the preferences

⚠️ Actually this is not working with Safari 16.5.1 (latest version), it seems there is a problem in recognizing custom methods added to an extended element, I added a comment on line 17:
```javascript
// WARNING: on Safari 'dialogOverlayElement.setupDialog' is undefined and raises the following error:
// Unhandled Promise Rejection: TypeError: dialogOverlayElement.setupDialog is not a function.
// >>> console.log(dialogOverlayElement['setupDialog']);
```

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
It seems that Safari doesn't support extending native elements like `<dialog>` using the `extends` property in `customElements.define`.

**Comment by justvanrossum** [comment]
> Actually this is not working with Safari 16.5.1 

The problem is with `<dialog is="dialog-overlay"></dialog>`, the `is` syntax is not yet supported in Safari: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/is#browser_compatibility

To be honest, I do not yet understand why we wouldn't just write `<dialog-overlay></dialog-overlay>`.

Btw. we may want to consider "dialog-overlay" to "modal-dialog".

**Comment by fabiocaccamo** [comment]
> To be honest, I do not yet understand why we wouldn't just write <dialog-overlay></dialog-overlay>

Because that works only for custom components that don't inherit from standard HTML elements.
So the only solution is to wrap a `<dialog>` element inside an autonomous custom element.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Components/Using_custom_elements#high-level_view

> Btw. we may want to consider "dialog-overlay" to "modal-dialog".

No problem 👍

**Comment by justvanrossum** [comment]
> Because that works only for custom components that don't inherit from standard HTML elements.

Ah, got it, thanks.

> So the only solution is to wrap a <dialog> element inside an autonomous custom element.

I suggest to do the opposize: have `dialog()` create a plain `<dialog>` element, and have the _contents_ be our custom element (as the single child of `<dialog>`):
```js
class DialogContents extends SimpleElement {
  // ...
}
```

How does that sound to you?

**Review by justvanrossum — COMMENTED** [review]
Looking very good, thanks!

I left a minor appearance suggestion.

I notice that often (always?) an items gets a focus ring:

image

It's not always the cancel button:

image

I don't see any changes in this PR that causes it, so maybe it is somehow a side effect of the `<dialog>` element? It looks like the focus ring you get when clicking on an item and then using the keyboard to navigate. Which isn't the case yet here.

Do you see it, too?

File: src/fontra/client/web-components/modal-dialog.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ export async function dialog(headline, message, buttonDefs, autoDismissTimeout)
 }
 
 export async function dialogSetup(headline, message, buttonDefs, autoDismissTimeout) {
-  const dialogOverlayElement = document.querySelector("dialog-overlay");
+  const dialogOverlayElement = document.querySelector("modal-dialog");
```
[the remark this answers is not in the document]
Comment (fabiocaccamo) [reply src/fontra/client/web-components/modal-dialog.js:16]: Or even `modalDialogElement`?

**Comment by justvanrossum** [comment]
Since we have key handler for the cancel and the default button, I don't see how focus makes any sense here.

If there is a text entry field, then sure, that should get focus.

But this general autofocus behavior is highly undesired. Can we disable it altogether?

**Comment by justvanrossum** [comment]
Or should the default button get the autofocus property?

**Comment by justvanrossum** [comment]
(Hm, not when there's a text entry. Urg.)

**Comment by fabiocaccamo** [comment]
Right, let's force the focus on the cancel button.

**Comment by justvanrossum** [comment]
> Right, let's force the focus on the cancel button.

What do you mean? It makes no sense to have the focus there at all.

**Comment by justvanrossum** [comment]
Possibly workaround: after the dialog is shown, find the focused element, and blur it unless it's a text input.

**Comment by fabiocaccamo** [comment]
@justvanrossum I think you can re-check it, here the update of the latest commits:

- I fixed the outline issue by having the initial focus on the dialog.

- The behaviour of the `Enter` key had a conflict with the native behaviour, eg. if a user start tabbing in the dialog and move the focus on the cancel button, pressing the `Enter` key should "click" the "Cancel" button and not the "Ok" button. The initial solution to this problem was to check the focused element (`document.activeElement`) when pressing `Enter` and if different by the initial one (dialog) it would have mean that the focus was moved to another element by the user. Unfortunately this doesn't work correctly because the value of `document.activeElement` is not updated correctly with elements inside the dialog. To achieve the same result in a different way I listen for the tab even, once received I store the "tabbed" action in a boolean variable, then when the user press the Enter key, if he hasn't tabbed yet, I automatically click the "Ok" button, otherwise I don't.

**Comment by fabiocaccamo** [comment]
Saving the last active element is no more necessary because we are using a native <dialog> element and the browser seems to correctly set the focus back to the last active element when a dialog is close.

Could you double check the outline issue on the +/- button in Chrome? I don't see it and I'm not able to reproduce it.

**Comment by justvanrossum** [comment]
> Could you double check the outline issue on the (+) / (-) sidebar buttons in Chrome? I don't see it nor able to reproduce it.

It's still there (in Chrome).

Go to a location where there is no source, then click the (+) button. In the dialog, hit the "enter" key. Now the dialog does its work, but immediately afterwards it pops up again, this time with the "Add" button disabled, since the source now already exists.

**Comment by justvanrossum** [comment]
Regarding the behavior where the "enter" key only works if you haven't tabbed to a different field: that is not correct. Then we have a button tha is displayed as the default button, but it doesn't work as a default button anymore.

I think the problem I showed has to do with the numeric input of the slider, and not the dialog. If the numeric input has the focus, hitting "enter" should blur the text input (and therefore update the slider position), but a subsequent "enter" should still cause the default button to be clicked. The numeric input behavior is correct in the axis sliders that are not in the dialog, so I suspect the "enter" accidentally bubbles to the dialog, and then _also_ triggers the click.

Let's treat this as a separate issue. It is a bit tricky, as the behavior also seems to differ between Safari and Chrome.

**Comment by fabiocaccamo** [comment]
> Regarding the behavior where the "enter" key only works if you haven't tabbed to a different field: that is not correct. Then we have a button tha is displayed as the default button, but it doesn't work as a default button anymore.

I don't agree here: if you tab and the focus moves on the "Cancel" button and you press "Enter", then the "Cancel" button must receive the "Enter" event (and be implicitly clicked), not the button that we consider the default one. 

In case I'm not understanding correctly, could you explain me what you would expect to do and what happens instead?

> I think the problem I showed has to do with the numeric input of the slider, and not the dialog. If the numeric input has the focus, hitting "enter" should blur the text input (and therefore update the slider position), but a subsequent "enter" should still cause the default button to be clicked. The numeric input behavior is correct in the axis sliders that are not in the dialog, so I suspect the "enter" accidentally bubbles to the dialog, and then also triggers the click.

Yes, a new issue would be more appropriate here. 
In this case the problem seems more bounded to the input / slider component inside the dialog that to the dialog component itself.

**Comment by fabiocaccamo** [comment]
> Then we have two conflicting concepts, that I'm not sure how to resolve

Yes, exactly.

> However, the issue that I experience is this: I tag to a slider's numeric input field, type a new value, but now "enter" updates the slider position, but after that I would expected "enter" to still "click" the default button.

I think that from a usability point of view, after having changed the input field value and pressed "enter", the focus will move to the next focusable element only when pressing "tab".

**Comment by justvanrossum** [comment]
> I think that from a usability point of view, after having changed the input field value and pressed "enter", the focus will move to the next focusable element only when pressing "tab".

What could happen instead (when hitting enter in a numeric input field) is that it doesn't focus a different element, but merele unfocuses (blurs) the numeric input, after which the enter key can be used to click the default button.

File: src/fontra/client/web-components/modal-dialog.js [hunk 2]
```diff
@@ -236,26 +234,33 @@ export class DialogOverlay extends SimpleElement {
...
+    this._tabbed = false;
   }
 
   _handleKeyDown(event) {
-    if (event.key == "Enter") {
-      if (!this.defaultButton?.classList.contains("disabled")) {
-        this.defaultButton?.click();
+    if (event.key === "Enter") {
+      // console.log(document.activeElement);
+      // unfortunately document.activeElement is always the whole dialog,
```
Comment (justvanrossum) [inline src/fontra/client/web-components/modal-dialog.js:249]: See findNestedActiveElement() function for an example of how to find the active element within a shadow-root active element:

https://github.com/googlefonts/fontra/blob/c80e68bf4bbb803aa73f8bbc0bbbe5a9746d34b0/src/fontra/client/core/utils.js#L316-L322
