### ISSUE TITLE
TypeError: navigator.clipboard.read is not a function

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/fontra#1412]
A user is facing issues with copy/paste. 

The console error is this:

```
Uncaught (in promise) TypeError: navigator.clipboard.read is not a function
   readFromClipboard http://localhost:8000/core/utils.5e2b9767.js:276
   _unpackClipboard http://localhost:8000/editor/editor.5e2b9767.js:1689
   doPaste http://localhost:8000/editor/editor.5e2b9767.js:1615
   callback http://localhost:8000/editor/editor.5e2b9767.js:1109
   keyDownHandler http://localhost:8000/editor/editor.5e2b9767.js:1306
   EditorController http://localhost:8000/editor/editor.5e2b9767.js:268
```

Environment of the user:
— macOS Ventura Version 13.1
— Crome [125.0.6422.113] 
— Firefox [126.0.1]

**Comment by ollimeier** [comment]
The user said, it works with Safari [Version 16.2 (18614.3.7.1.5)]

**Comment by ollimeier** [comment]
@ReymundS 
Info for you from @justvanrossum :
Possible workaround for Firefox: go to “about:config” (paste that in the URL bar), then search for “dom.event.clipboardevents.enabled”, and set that to “true”.

Please let us know if this works for you?

**Comment by justvanrossum** [comment]
Ok thanks, so that's not it, either.

When trying to copy/paste did either of Chrome or Firefox show you a dialog, asking for permission to export the clipboard, or permission to paste?

Is the error message any different in Chrom vs Firefox?

**Comment by ollimeier** [comment]
<img width="1651" alt="Screenshot 2024-05-30 at 15 20 41" src="https://github.com/googlefonts/fontra/assets/21055547/16f2f8dc-b583-4119-b3a6-6d538aca775d">

**Comment by ReymundS** [comment]
Ok! Chrome works now — thank you!

Firefox: No dialog. ›cut‹ and ›copy‹ seems to work, there is no message. But when I try to paste the message from above appears.

**Comment by ollimeier** [comment]
@ReymundS @justvanrossum 
I am closing this issue because it looks like it's related to browser settings. Feel free to open it again, if necessary.
